# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!x|
  displayName: 'Run a one-line script'


- task: katalonTask@1
  inputs:
    version: '8.2.0'
    executeArgs: 'katalonc -noSplash -runMode=console -projectPath= "${WORK_DIR}/TestProjectWeb.prj" -retry=0 -testSuiteCollectionPath="Test Suites/TSCollection01.ts " -executionProfile="default" -browserType="Chrome" -apiKey="2a2b77d0-e68c-42e2-8802-1152239931e8" -testOpsReleaseId=152827 -testOpsProjectId=222377'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
