<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DDTExcelFile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>565a5968-6a25-47a4-9260-381c6a3843c3</testSuiteGuid>
   <testCaseLink>
      <guid>a7f489fa-b72c-4b77-a005-cdb2558f6ba0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HealthcareApp/DataTesting/TC005_DataDriven</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ce8cfb57-e30e-40fd-9f2f-8b150f0b117e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/AutomationData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>ce8cfb57-e30e-40fd-9f2f-8b150f0b117e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userName</value>
         <variableId>eb195f27-3fa3-4ee0-84eb-d0faeef61fcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ce8cfb57-e30e-40fd-9f2f-8b150f0b117e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>e95d8ba4-e9b8-4835-a362-c7c12b4e5498</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
