<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDriverInternalDataSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>cd4c89f8-5a29-486f-93f3-44e25ffaf2a4</testSuiteGuid>
   <testCaseLink>
      <guid>0f1c9cf6-1437-4c62-b00a-c8a393775076</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HealthcareApp/TC002_InvalidLogin</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9a7598a1-1b95-41e4-bb56-cc2a1d244723</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/InternalTestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>9a7598a1-1b95-41e4-bb56-cc2a1d244723</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userName</value>
         <variableId>6036c524-c4e1-4e91-969b-0475b6203f4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9a7598a1-1b95-41e4-bb56-cc2a1d244723</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>11dd605b-0858-4c70-8ce0-ffe592f775e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fa2cf5b-00e6-43a2-8fe7-34f8b7c21797</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
