<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_dashoard</name>
   <tag></tag>
   <elementGuidId>66b2265b-c439-4b16-94b0-1be8ff15c26f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;sfxdash-1633507777607-394566&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name=&quot;sfxdash-1633507777607-394566&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sfxdash-1633507777607-394566</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>dashboard</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://katalon-inc--demo.lightning.force.com/desktopDashboards/dashboardApp.app?dashboardId=01Z2x000000dEgwEAE&amp;displayMode=readonly&amp;networkId=000000000000000&amp;context=embedded&amp;userId=0055D000004P5dmQAC</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cd_frame_id_</name>
      <type>Main</type>
      <value>708f0cef6e0d7a0d26160e2d5f10a9ed</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/div[@class=&quot;container homeLanding&quot;]/div[@class=&quot;flexipagePage&quot;]/div[@class=&quot;responsiveContents homeDesktopTemplate&quot;]/div[@class=&quot;colMain&quot;]/div[@class=&quot;top&quot;]/div[@class=&quot;flexipageComponent&quot;]/div[@class=&quot;embeddedDashboardContainer&quot;]/div[@class=&quot;dashboardTopLevelContainer desktopDashboardsDashboard&quot;]/div[@class=&quot;dashboardContainer&quot;]/iframe[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='sfxdash-1633507777607-394566']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div/div/div/div/div/div/div/div/div/div[2]/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
