name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '8.1.0'
          projectPath: ${{ github.workspace }}
          args: 'katalonc -noSplash -retry=0 -testSuitePath="Test Suites/API_TestSuite" -browserType="Chrome" -apiKey="2a2b77d0-e68c-42e2-8802-1152239931e8" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true'
    - name: HTML Preview
      uses: pavi2410/html-preview-action@v2
      with:
          html_file: '*.html'
