name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}



jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '8.1.0'
          projectPath: ${{ github.workspace }}
          args: 'katalonc -noSplash -retry=0 -testSuiteCollectionPath="Test Suites/TSCollection01" -apiKey="2a2b77d0-e68c-42e2-8802-1152239931e8" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true'
